### ISSUE TITLE
Hard-coded, default express secret

### ISSUE THREAD

**Issue by gonzalezjo** [QuantumStack/CMULab#22]
See: https://github.com/QuantumStack/CMULab/blob/master/server/app.js#L76

The secret should be initialized from some safe RNG, like, Crypto.getRandomValues, or through some environment variable.

**Comment by gonzalezjo** [comment]
Perfect.

**Comment by adityarpillai** [comment]
Thanks for submitting the issue. This has been patched and deployed.
